# .github/workflows/docker-build.yml
name: Docker Build

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      ecr-repo:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t my-app:${{ inputs.image-tag }} .
          echo "DOCKER_IMAGE=my-app:${{ inputs.image-tag }}" >> $GITHUB_ENV

      - name: Tag Docker image
        run: docker tag ${{ env.DOCKER_IMAGE }} ${{ inputs.ecr-repo }}:${{ inputs.image-tag }}

      - name: Push Docker image
        run: docker push ${{ inputs.ecr-repo }}:${{ inputs.image-tag }}
