# .github/workflows/main.yml
name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      image-tag: ${{ github.sha }}
      ecr-repo: ${{ secrets.ECR_REPO }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
